name: 'setup-node'
description: 'Composite action to setup Node.js, restore npm cache and install dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  cache-dependency-path:
    description: 'Glob(s) to hash for npm cache key'
    required: false
    default: '**/package-lock.json'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js (with npm cache)
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore npm cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.npm/_cacache
        key: ${{ runner.os }}-npm-${{ hashFiles(inputs.cache-dependency-path) }}

    - name: Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          apps/frontend/node_modules
          apps/admin-panel/node_modules
          packages/**/node_modules
        key: ${{ runner.os }}-node-modules-${{ inputs.node-version }}-${{ hashFiles(inputs.cache-dependency-path) }}

    - name: Restore frontend node_modules cache
      uses: actions/cache@v4
      with:
        path: apps/frontend/node_modules
        key: ${{ runner.os }}-node-modules-frontend-${{ inputs.node-version }}-${{ hashFiles('apps/frontend/package-lock.json','apps/frontend/package.json') }}

    - name: Restore admin-panel node_modules cache
      uses: actions/cache@v4
      with:
        path: apps/admin-panel/node_modules
        key: ${{ runner.os }}-node-modules-admin-${{ inputs.node-version }}-${{ hashFiles('apps/admin-panel/package-lock.json','apps/admin-panel/package.json') }}

    - name: Restore packages shared node_modules cache
      uses: actions/cache@v4
      with:
        path: packages/shared/node_modules
        key: ${{ runner.os }}-node-modules-packages-shared-${{ inputs.node-version }}-${{ hashFiles('packages/shared/package-lock.json','packages/shared/package.json') }}

    - name: Restore packages ui node_modules cache
      uses: actions/cache@v4
      with:
        path: packages/ui/node_modules
        key: ${{ runner.os }}-node-modules-packages-ui-${{ inputs.node-version }}-${{ hashFiles('packages/ui/package-lock.json','packages/ui/package.json') }}

    - name: Install dependencies
      run: npm ci
      shell: bash
