name: 'setup-node'
description: 'Composite action to setup Node.js, restore npm cache and install dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  cache-dependency-path:
    description: 'Glob(s) to hash for npm cache key'
    required: false
    default: '**/package-lock.json'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js (with npm cache)
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore npm cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.npm/_cacache
        key: ${{ runner.os }}-npm-${{ hashFiles(inputs.cache-dependency-path) }}

    - name: Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          apps/frontend/node_modules
          apps/admin-panel/node_modules
          packages/**/node_modules
        key: ${{ runner.os }}-node-modules-${{ inputs.node-version }}-${{ hashFiles(inputs.cache-dependency-path) }}

    - name: Install dependencies
      run: npm ci
      shell: bash
